ci:
  autoupdate_schedule: monthly
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.13.3
  hooks:
    - id: ruff-check
    - id: ruff-format
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.34.0
  hooks:
    - id: check-github-workflows
    - id: check-readthedocs
