import marshmallow as ma
from . import marshmallow_bonus as ma_bonus_fields
from .abstract import BaseField
from typing import Any

class StringField(BaseField, ma.fields.String): ...
class UUIDField(BaseField, ma.fields.UUID): ...
class NumberField(BaseField, ma.fields.Number): ...
class IntegerField(BaseField, ma.fields.Integer): ...
class DecimalField(BaseField, ma.fields.Decimal): ...
class BooleanField(BaseField, ma.fields.Boolean): ...
class FloatField(BaseField, ma.fields.Float): ...
class DateTimeField(BaseField, ma.fields.DateTime): ...
class NaiveDateTimeField(BaseField, ma.fields.NaiveDateTime): ...
class AwareDateTimeField(BaseField, ma.fields.AwareDateTime): ...
class DateField(BaseField, ma.fields.Date): ...
class UrlField(BaseField, ma.fields.Url): ...
class EmailField(BaseField, ma.fields.Email): ...
class ConstantField(BaseField, ma.fields.Constant): ...

class DictField(BaseField, ma.fields.Dict):
    default: Any
    missing: Any
    def __init__(self, *args, **kwargs): ...
    def as_marshmallow_field(self): ...

class ListField(BaseField, ma.fields.List):
    default: Any
    missing: Any
    def __init__(self, *args, **kwargs): ...
    def map_to_field(self, mongo_path, path, func) -> None: ...
    def as_marshmallow_field(self): ...

URLField = UrlField
StrField = StringField
BoolField = BooleanField
IntField = IntegerField

class ObjectIdField(BaseField, ma_bonus_fields.ObjectId): ...

class ReferenceField(BaseField, ma_bonus_fields.Reference):
    reference_cls: Any
    document: Any
    def __init__(self, document, *args, reference_cls=..., **kwargs) -> None: ...
    @property
    def document_cls(self): ...

class GenericReferenceField(BaseField, ma_bonus_fields.GenericReference):
    reference_cls: Any
    def __init__(self, *args, reference_cls=..., **kwargs) -> None: ...

class EmbeddedField(BaseField, ma.fields.Nested):
    embedded_document: Any
    def __init__(self, embedded_document, *args, **kwargs) -> None: ...
    @property
    def embedded_document_cls(self): ...
    def map_to_field(self, mongo_path, path, func) -> None: ...
    def as_marshmallow_field(self): ...
