import marshmallow as ma
from .abstract import BaseValidator

class URL(BaseValidator, ma.validate.URL): ...
class Email(BaseValidator, ma.validate.Email): ...
class Range(BaseValidator, ma.validate.Range): ...
class Length(BaseValidator, ma.validate.Length): ...
class Equal(BaseValidator, ma.validate.Equal): ...
class Regexp(BaseValidator, ma.validate.Regexp): ...
class Predicate(BaseValidator, ma.validate.Predicate): ...
class NoneOf(BaseValidator, ma.validate.NoneOf): ...
class OneOf(BaseValidator, ma.validate.OneOf): ...
class ContainsOnly(BaseValidator, ma.validate.ContainsOnly): ...
